--[[
  updater.lua -- ComputerCraft / CC:Tweaked self-update helper

  Fetches a fresh copy of a program from the repository, checks it over, and
  installs it. Used as a library by the turtle programs, and runnable on its
  own to force a check:

    updater                 check everything installed
    updater sweeper.lua     check one program
    updater restore sweeper.lua    put the previous version back

  A program carries its own version as a line near the top:

    local VERSION = "1.0.0"

  and the same line in the copy on the server is what decides whether there
  is anything to install. Bumping it is what rolls an update out to a fleet;
  editing anything else does not.

  NOTHING HERE IS LOAD-BEARING. A computer with no HTTP, no network, or a
  server that hands back nonsense carries on running the program it already
  has. The one thing this module will not do is leave a turtle with a program
  that does not compile, so every download is parsed before it is written --
  a truncated body is the realistic failure, and a turtle that writes half a
  file over itself is a turtle somebody has to walk out to.

  INSTALL
    wget https://raw.githubusercontent.com/erinlkolp/computercraft-scripts/refs/heads/main/lib/updater.lua
]]

local updater = {}

-- Declared the same way the turtle programs declare theirs, because this
-- module is in SOURCES too and has to be able to replace itself.
local VERSION = "1.0.0"

updater.VERSION = VERSION

updater.REPO   = "erinlkolp/computercraft-scripts"
updater.BRANCH = "main"

-- Installed name -> where it lives in the repository. A program that isn't
-- in here is somebody else's and is left well alone.
updater.SOURCES = {
  ["sweeper.lua"]   = "turtles/sweeper.lua",
  ["flattener.lua"] = "turtles/flattener.lua",
  ["updater.lua"]   = "lib/updater.lua",
}

-- Marker written into any startup file we generate. We overwrite a file
-- carrying it and never touch one that isn't.
local STARTUP_MARKER = "-- generated by updater.lua -- safe to delete"

local BACKUP_SUFFIX  = ".bak"

-- A truncated download can still compile, if the cut happens to land on a
-- statement boundary. What gives it away is the size: a real release is
-- never a fraction of the version it replaces.
local SHRINK_LIMIT   = 0.5

-- ============================================================
-- VERSIONS
-- ============================================================

function updater.rawUrl(repoPath)
  return "https://raw.githubusercontent.com/" .. updater.REPO ..
         "/refs/heads/" .. updater.BRANCH .. "/" .. repoPath
end

-- Read the version out of a program's source text.
function updater.parseVersion(text)
  if type(text) ~= "string" then return nil end
  return text:match('local%s+VERSION%s*=%s*"([%d%.]+)"')
end

local function parts(v)
  local out = {}
  for n in tostring(v or ""):gmatch("%d+") do out[#out + 1] = tonumber(n) end
  return out
end

-- Numeric, component by component, so 1.10.0 beats 1.9.0 the way text
-- comparison would not. Missing components count as zero: 1.2 == 1.2.0.
function updater.isNewer(candidate, current)
  local a, b = parts(candidate), parts(current)
  for i = 1, math.max(#a, #b) do
    local x, y = a[i] or 0, b[i] or 0
    if x ~= y then return x > y end
  end
  return false
end

-- ============================================================
-- DISK
-- ============================================================

local function readFile(path)
  local h = fs.open(path, "r")
  if not h then return nil end
  local contents = h.readAll()
  h.close()
  return contents
end

local function writeFile(path, contents)
  local h = fs.open(path, "w")
  if not h then return false end
  h.write(contents)
  h.close()
  return true
end

-- ============================================================
-- FETCH
-- ============================================================

-- Returns the body, or nil plus a reason. Never throws: a computer with the
-- HTTP API switched off entirely still has to get through this.
local function fetch(url)
  if type(http) ~= "table" or type(http.get) ~= "function" then
    return nil, "no http api"
  end

  local ok, handle, err = pcall(http.get, url)
  if not ok then return nil, "request failed" end
  if not handle then return nil, tostring(err or "no response") end

  local read, body = pcall(handle.readAll)
  pcall(handle.close)
  if not read or type(body) ~= "string" then return nil, "unreadable response" end

  return body
end

-- ============================================================
-- CHECK
-- ============================================================

-- Look for a newer copy of `name` and install it if there is one.
--
-- Returns one of:
--   "updated"  a newer version is now on disk; the caller should reboot
--   "current"  nothing newer is published
--   "offline"  could not reach the server, or there is no HTTP at all
--   "rejected" something came back but it was not fit to install
--   "unknown"  no source is registered for this program
-- plus a short detail string for printing.
function updater.check(name, currentVersion)
  local source = updater.SOURCES[name]
  if not source then return "unknown", "no source registered for " .. tostring(name) end

  local body, why = fetch(updater.rawUrl(source))
  if not body then return "offline", why end

  local fetchedVersion = updater.parseVersion(body)
  if not fetchedVersion then
    return "rejected", "no VERSION line in the downloaded copy"
  end

  if not updater.isNewer(fetchedVersion, currentVersion) then
    return "current", "v" .. tostring(currentVersion) .. " is up to date"
  end

  -- The check that really matters. A body that does not parse is a truncated
  -- download, and writing it over the program strands the turtle.
  local chunk, syntaxErr = load(body, "@" .. name, "t", {})
  if not chunk then
    return "rejected", "downloaded copy does not compile: " .. tostring(syntaxErr)
  end

  local previous = readFile(name)
  if previous and #body < #previous * SHRINK_LIMIT then
    return "rejected", "downloaded copy is suspiciously small (" .. #body ..
                       " bytes against " .. #previous .. ")"
  end

  if previous then writeFile(name .. BACKUP_SUFFIX, previous) end

  if not writeFile(name, body) then
    return "rejected", "could not write " .. name
  end

  return "updated", "v" .. tostring(currentVersion) .. " -> v" .. fetchedVersion
end

-- Put back whatever was there before the last update.
function updater.restore(name)
  local backup = readFile(name .. BACKUP_SUFFIX)
  if not backup then return false, "no backup of " .. name end
  if not writeFile(name, backup) then return false, "could not write " .. name end
  return true, "restored the previous " .. name
end

-- ============================================================
-- STARTUP
-- ============================================================

-- A reboot with no startup file leaves the turtle sitting at a prompt, which
-- for a turtle at the bottom of a hole is no better than a bricked one. So
-- guarantee it comes back up running the same program.
--
-- Returns "written", "current", or "foreign" -- the last meaning somebody
-- hand-wrote a startup file, which we do not touch.
function updater.ensureStartup(name)
  local wanted = STARTUP_MARKER .. "\n" ..
                 'shell.run("' .. name .. '")\n'

  local existing = readFile("startup.lua")
  if existing then
    if existing == wanted then return "current", "startup.lua already runs " .. name end
    if not existing:find(STARTUP_MARKER, 1, true) then
      return "foreign", "startup.lua was written by hand; leaving it alone"
    end
  end

  if not writeFile("startup.lua", wanted) then
    return "foreign", "could not write startup.lua"
  end
  return "written", "startup.lua will run " .. name
end

-- ============================================================
-- PROGRAM MODE
-- ============================================================

-- Only when run as a program, not when loaded as a library.
local function main(args)
  if args[1] == "restore" then
    local name = args[2]
    if not name then
      print("usage: updater restore <program>")
      return
    end
    local ok, msg = updater.restore(name)
    print((ok and "  " or "  ! ") .. msg)
    return
  end

  local names = {}
  if args[1] then
    names[1] = args[1]
  else
    for name in pairs(updater.SOURCES) do
      if fs.exists(name) then names[#names + 1] = name end
    end
    table.sort(names)
  end

  if #names == 0 then
    print("Nothing installed that I know how to update.")
    return
  end

  for _, name in ipairs(names) do
    local installed = updater.parseVersion(readFile(name) or "") or "0.0.0"
    local status, detail = updater.check(name, installed)
    print(name .. ": " .. status .. " (" .. tostring(detail) .. ")")
  end
end

-- `...` is the program's arguments when run from the shell, and empty when
-- the file is loaded as a library, which is how we tell the two apart.
local args = { ... }
if args[1] ~= nil or (shell and shell.getRunningProgram and
                      shell.getRunningProgram():find("updater", 1, true)) then
  main(args)
end

return updater
